---
- name: install docker on ubuntu
  hosts: all
  vars:
    # We'll controll the CE version of docker here
    docker_ce: 17.06.2~ce-0~ubuntu
  tasks:
    - name: Register fact -> uname-r
      shell: uname -r
      register: this_kernel
    - name: Register fact -> docker apt key
      shell: apt-key list | grep 'docker@docker'
      register: docker_apt_key
      ignore_errors: yes
    - name: install ubuntu docker apt key
      become: yes
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
      when: "(not ansible_check_mode) and ('docker@docker' not in docker_apt_key.stdout)"
    - name: add apt repository
      become: yes
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
    - name: install additional goodies for docker support
      become: yes
      apt: name={{ item }} state=present cache_valid_time=3600
      when: not ansible_check_mode
      with_items:
        - linux-image-extra-{{ this_kernel.stdout }}
        - linux-image-extra-virtual
        - software-properties-common
        - docker-ce={{ docker_ce }}
    - name: get current user
      local_action: command whoami
      register: username_on_host
    - name: add docker to user groups
      become: yes
      user:
        name: "{{ username_on_host.stdout }}"
        groups: docker
        append: yes
        state: present
    - name: enable upstart docker
      become: yes
      service:
        name: docker
        enabled: yes
        state: started
