---
- name: personalize home directory for a user
  hosts: localhost
  connection: local
  tasks:
    - name: set the home directory
      set_fact:
        home: "{{ lookup('env','HOME') }}"
    - name: set to source bashrc_local
      lineinfile:
        dest: "{{ home }}/.bashrc"
        line: "source .bashrc.local"
        insertbefore: '^# enable programmable completion'
    - name: set to flush history after every command
      lineinfile:
        dest: "{{ home }}/.bashrc"
        line: "PROMPT_COMMAND='history -a;history -n'"
        insertafter: '^shopt -s histappend'
    - name: create config dir
      file: state=directory path="{{ home }}/.config/terminator" recurse=yes
    - name: configure terminator template
      template:
        dest: "{{ home }}/.config/terminator/config"
        src: "template.terminator"
    - name: configure local aliases
      template:
        dest: "{{ home }}/.bash_aliases"
        src: "template.bash_aliases"
    - name: configure bashrc.local
      template:
        dest: "{{ home }}/.bashrc.local"
        src: "template.bashrc.local"
    - name: install sexy bash prompt
      become: yes
      git:
        repo: https://github.com/twolfson/sexy-bash-prompt
        depth: 1
        dest: /opt/sexy-bash
    - name: install sexy bash prompt
      shell: make install
      args:
        chdir: /opt/sexy-bash
        creates: "{{ home }}/.bash_prompt"
    - name: force install the latest sexy bash prompt
      when: force is defined
      shell: make install
      args:
        chdir: /opt/sexy-bash
