---
- name: Set up disabling screen saver
  hosts: devbox
  tasks:
    - name: register power light locker setting
      shell: gsettings get org.gnome.settings-daemon.plugins.power sleep-inactive-ac-timeout
      register: power
